name: Terraform Audit Account

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/audit-account/**"
      - ".github/workflows/terraform-audit-account.yml"
      - ".github/workflows/terraform-spoke-template.yml"
  push:
    branches:
      - main
    paths:
      - "terraform/audit-account/**"
      - ".github/workflows/terraform-audit-account.yml"
      - ".github/workflows/terraform-spoke-template.yml"

jobs:
  terraform:
    uses: ./.github/workflows/terraform-spoke-template.yml
    with:
      spoke_name: Audit Account
      working_directory: terraform/audit-account
      artifact_name: audit-account-tfplan
      apply_environment: audit-prod
      concurrency_group: terraform-audit-account
    secrets:
      role_to_assume: ${{ secrets.AWS_OIDC_ROLE_ARN_AUDIT }}
