name: Terraform Aggregator Account

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/aggregator-account/**"
      - ".github/workflows/terraform-aggregator-account.yml"
      - ".github/workflows/terraform-spoke-template.yml"
  push:
    branches:
      - main
    paths:
      - "terraform/aggregator-account/**"
      - ".github/workflows/terraform-aggregator-account.yml"
      - ".github/workflows/terraform-spoke-template.yml"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform-spoke-template.yml
    with:
      spoke_name: Aggregator Account
      working_directory: terraform/aggregator-account
      artifact_name: aggregator-account-tfplan
      apply_environment: aggregator-prod
      concurrency_group: terraform-aggregator-account
    secrets:
      role_to_assume: ${{ secrets.AWS_OIDC_ROLE_ARN_AGGREGATOR }}
